
data:
  map_directory: 'C:\Users\thomas\AppData\Local\Ankama\zaap\retro\resources\app\retroclient\data\maps\'

network:
  log: true
  interface: '\\Device\\NPF_{F23B8BB9-F7D0-4D4B-8646-616C19D4390A}'